# Generated by Django 2.0.6 on 2018-11-30 07:33

import askcompany.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(blank=True, upload_to=askcompany.utils.uuid_upload_to),
        ),
    ]
